#  Chi-Square (χ²) Test

The **Chi-Square (χ²) Test** is a statistical hypothesis test used to determine whether there is a **significant association or relationship between two categorical variables**.

Unlike the Z-Test and T-Test, which compare **means**, the Chi-Square Test compares **frequencies (counts)**.

#### Chi-Square Formula

```text
           (Observed − Expected)²
χ² = Σ -----------------------------
              Expected

Where:

- O = Observed Frequency
- E = Expected Frequency

#### Import Libraries

In [1]:
import pandas as pd 
from scipy.stats import chi2_contingency

#### Create a Sample data

In [2]:
data = {
    "Gender": [
        "Male","Male","Male","Male","Male",
        "Female","Female","Female","Female","Female"
    ],
    "Product": [
        "A","A","B","B","A",
        "A","B","B","B","A"
    ]
}
df = pd.DataFrame(data)
df

   Gender Product
0    Male       A
1    Male       A
2    Male       B
3    Male       B
4    Male       A
5  Female       A
6  Female       B
7  Female       B
8  Female       B
9  Female       A

#### Create a Contingency Table

In [3]:
table = pd.crosstab(
    df["Gender"],
    df["Product"]
)
table

Product  A  B
Gender
Female   2  3
Male     3  2

#### Perform Chi-Square Test

In [4]:
chi2, p_value, dof, expected = chi2_contingency(table)
print("Chi-Square Statistic :", round(chi2,3))
print("P Value :", round(p_value,4))
print("Degrees of Freedom :", dof)

Chi-Square Statistic : 0.0
P Value : 1.0
Degrees of Freedom : 1

#### Expected Frequency

In [5]:
expected_df = pd.DataFrame(
    expected,
    index=table.index,
    columns=table.columns
)
expected_df

Product    A    B
Gender
Female   2.5  2.5
Male     2.5  2.5

#### Decision making

In [6]:
alpha = 0.05
if p_value < alpha:
    print("Reject the Null Hypothesis")
else:
    print("Fail to Reject the Null Hypothesis")

Fail to Reject the Null Hypothesis

#### Conclusion

In [7]:
if p_value < alpha:
    print("There is a significant relationship between Gender and Product Preference.")
else:
    print("There is no significant relationship between Gender and Product Preference.")

There is no significant relationship between Gender and Product Preference.