# Label Encoding

Label Encoding is a technique used to convert categorical values into numerical values.

Machine learning algorithms generally work with numerical data, so categorical features often need to be transformed.

For example:

Male → 1
Female → 0

Label Encoding assigns a unique integer to each category.

#### Why Do We Need Encoding?

Machine learning models generally cannot directly process text categories such as:

- Male
- Female
- Lahore
- Karachi
- Bachelor
- Master

Therefore, categorical values need to be converted into numerical representations.

Encoding is an important step in preprocessing categorical features.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Gender": ["Male", "Female", "Female", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"]
})

df

   Gender       City
0    Male     Lahore
1  Female    Karachi
2  Female  Islamabad
3    Male     Lahore
4  Female    Karachi

#### LabelEncoder

Scikit-learn provides `LabelEncoder` for converting categorical labels into integers.

Each unique category receives a numerical label.

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
encoder = LabelEncoder()

df["Gender_Encoded"] = encoder.fit_transform(df["Gender"])

df

   Gender       City  Gender_Encoded
0    Male     Lahore               1
1  Female    Karachi               0
2  Female  Islamabad               0
3    Male     Lahore               1
4  Female    Karachi               0

In [4]:
print("Classes:", encoder.classes_)

Classes: ['Female' 'Male']

In [5]:
mapping = dict(
    zip(
        encoder.classes_,
        encoder.transform(encoder.classes_)
    )
)

mapping

{'Female': np.int64(0), 'Male': np.int64(1)}

In [6]:
city_encoder = LabelEncoder()

df["City_Encoded"] = city_encoder.fit_transform(df["City"])

df

   Gender       City  Gender_Encoded  City_Encoded
0    Male     Lahore               1             2
1  Female    Karachi               0             1
2  Female  Islamabad               0             0
3    Male     Lahore               1             2
4  Female    Karachi               0             1

In [7]:
city_mapping = dict(
    zip(
        city_encoder.classes_,
        city_encoder.transform(city_encoder.classes_)
    )
)

city_mapping

{'Islamabad': np.int64(0), 'Karachi': np.int64(1), 'Lahore': np.int64(2)}