# Plotly Express Basics

**Author:** Muhammad Anas

Plotly Express is a high-level API of the Plotly library that allows users to create interactive visualizations using concise and readable code.

Some key features include:

- Interactive charts
- Hover tooltips
- Zoom and pan functionality
- Built-in legends
- Easy customization
- Support for many chart types
- Integration with Pandas DataFrames

It is widely used for dashboards, business analytics, and exploratory data analysis.

Plotly Express provides several advantages:

- Interactive visualizations by default.
- Less code compared to traditional plotting libraries.
- Beautiful built-in themes.
- Easy integration with Pandas.
- Excellent for dashboards and web applications.
- Professional-quality visualizations.

#### Installing plotly

In [1]:
pip install plotly

Collecting plotly
  Using cached plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in f:\Anas\DATA_SCIENCE_POTPOLIO\.venv\Lib\site-packages (from plotly) (26.3)
Using cached plotly-6.9.0-py3-none-any.whl (9.9 MB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.24.0 plotly-6.9.0
Note: you may need to restart the kernel to use updated packages.

#### Importing libraries

In [2]:
import plotly.express as px
import pandas as pd

print("Plotly Express Imported Successfully!")

Plotly Express Imported Successfully!

#### Loading a Built-in Dataset

Plotly Express provides several built-in datasets that are useful for learning and experimentation.

In this notebook, we will use the **tips** dataset.

In [3]:
tips = px.data.tips()

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
tips.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [5]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

#### Creating Your First Interactive Plot

The `scatter()` function creates an interactive scatter plot.

Unlike Matplotlib, Plotly charts allow users to zoom, pan, and hover over data points without additional code.

In [6]:
fig = px.scatter(
    tips,
    x="total_bill",
    y="tip"
)

fig.show()

#### Adding Colors

The `color` parameter groups observations using different colors.

In [7]:
fig = px.scatter(
    tips,
    x="total_bill",
    y="tip",
    color="sex"
)

fig.show()

#### Adding Hover Information

Hover labels display additional information when the mouse moves over a data point.

In [8]:
fig = px.scatter(
    tips,
    x="total_bill",
    y="tip",
    color="sex",
    hover_data=["day", "time", "size"]
)

fig.show()

#### Customizing Titles and Labels

Plotly Express allows us to customize chart titles and axis labels using simple parameters.

In [9]:
fig = px.scatter(
    tips,
    x="total_bill",
    y="tip",
    color="sex",
    title="Total Bill vs Tip",
    labels={
        "total_bill": "Total Bill ($)",
        "tip": "Tip ($)"
    }
)

fig.show()

#### Available Built-in Datasets

Some useful Plotly datasets include:

- tips
- iris
- gapminder
- stocks
- medals_long
- election
- wind
- experiment

In [10]:
iris = px.data.iris()

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [11]:
fig = px.scatter(
    tips,
    x="total_bill",
    y="tip",
    color="sex",
    size="size",
    hover_name="day",
    title="Interactive Scatter Plot"
)

fig.show()