#### Stemming in NLP

Stemming is a Natural Language Processing (NLP) technique used to reduce words to a simpler base form called a **stem**.

The main idea is to remove prefixes or suffixes from words so that different forms of a word can be treated as related.

For example:

```text
playing   → play
played    → play
plays     → play

#### Stemming vs Lemmatization

Stemming and lemmatization both attempt to reduce words to a simpler form, but they work differently.

#### Stemming

Uses rules to remove parts of words.

```text
studies → studi
playing → play

#### Import nltk

In [1]:
import nltk

####  Porter Stemmer

The **Porter Stemmer** is one of the most commonly used traditional stemming algorithms.

It applies a series of linguistic rules to remove common word suffixes.

For example:

```text
playing    → play
played     → play
studies    → studi
connection → connect

In [2]:
from nltk.stem import PorterStemmer

# Create stemmer
porter = PorterStemmer()

words = [
    "play",
    "playing",
    "played",
    "plays",
    "studies",
    "studying",
    "connection",
    "connected"
]

for word in words:
    print(f"{word:15} → {porter.stem(word)}")

play            → play
playing         → play
played          → play
plays           → play
studies         → studi
studying        → studi
connection      → connect
connected       → connect

####  Snowball Stemmer

The **Snowball Stemmer** is an improved stemming framework that supports multiple languages.

For English, it is commonly used as an alternative to the Porter Stemmer.

It generally provides more consistent stemming results while remaining relatively fast.

In [3]:
from nltk.stem import SnowballStemmer

# Create English Snowball Stemmer
snowball = SnowballStemmer("english")

for word in words:
    print(f"{word:15} → {snowball.stem(word)}")

play            → play
playing         → play
played          → play
plays           → play
studies         → studi
studying        → studi
connection      → connect
connected       → connect

#### Compare Stemming Algorithms

Different stemming algorithms can produce different stems for the same word.

Therefore, it is useful to compare their results.

We will compare:

- Porter Stemmer
- Snowball Stemmer

In [4]:
# Compare Porter and Snowball

for word in words:
    porter_result = porter.stem(word)
    snowball_result = snowball.stem(word)

    print(
        f"{word:15} → "
        f"Porter: {porter_result:12} | "
        f"Snowball: {snowball_result}"
    )

play            → Porter: play         | Snowball: play
playing         → Porter: play         | Snowball: play
played          → Porter: play         | Snowball: play
plays           → Porter: play         | Snowball: play
studies         → Porter: studi        | Snowball: studi
studying        → Porter: studi        | Snowball: studi
connection      → Porter: connect      | Snowball: connect
connected       → Porter: connect      | Snowball: connect

#### Apply Stemming to a Sentence

Stemming is usually performed on individual tokens rather than directly on an entire sentence.

For example:

```text
"Customers are purchasing products"

In [5]:
sentence = "Customers are purchasing products and receiving discounts"

tokens = sentence.lower().split()

stemmed_tokens = [
    porter.stem(word)
    for word in tokens
]

print("Original Tokens:")
print(tokens)

print("\nStemmed Tokens:")
print(stemmed_tokens)

Original Tokens:
['customers', 'are', 'purchasing', 'products', 'and', 'receiving', 'discounts']

Stemmed Tokens:
['custom', 'are', 'purchas', 'product', 'and', 'receiv', 'discount']

####  Apply Stemming to Email Data

Now we will apply stemming to our Email Spam Detection dataset.

We will use the cleaned text created in the previous text-cleaning notebook.

The process will be:

```text
Clean Email
     ↓
Tokenization
     ↓
Porter Stemmer
     ↓
Stemmed Email

In [8]:
import pandas as pd
import re
import string
# Load dataset
df = pd.read_csv(
    r"F:\Anas\DATA_SCIENCE_POTPOLIO\12-Natural-Language-Processing\00_NLP_Basics\combined_data.csv"
)

# Basic cleaning function from previous notebook
def clean_text(text):
    text = text.lower()
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        " ",
        text
    )
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


# Clean emails
df["clean_text"] = df["text"].apply(clean_text)

In [9]:
# Display result
df[["text", "clean_text"]].head()

,text,clean_text
0,ounce feather bowl hummingbird opec moment ala...,ounce feather bowl hummingbird opec moment ala...
1,wulvob get your medircations online qnb ikud v...,wulvob get your medircations online qnb ikud v...
2,computer connection from cnn com wednesday es...,computer connection from cnn com wednesday esc...
3,university degree obtain a prosperous future m...,university degree obtain a prosperous future m...
4,thanks for all your answers guys i know i shou...,thanks for all your answers guys i know i shou...

#### Creating a stemming function

In [10]:
# Create stemming function

def stem_text(text):
    tokens = text.split()

    stemmed_tokens = [
        porter.stem(word)
        for word in tokens
    ]

    return " ".join(stemmed_tokens)

In [11]:
df["stemmed_text"] = df["clean_text"].apply(stem_text)

df[["text", "clean_text", "stemmed_text"]].head()

,text,clean_text,stemmed_text
0,ounce feather bowl hummingbird opec moment ala...,ounce feather bowl hummingbird opec moment ala...,ounc feather bowl hummingbird opec moment alab...
1,wulvob get your medircations online qnb ikud v...,wulvob get your medircations online qnb ikud v...,wulvob get your medirc onlin qnb ikud viagra e...
2,computer connection from cnn com wednesday es...,computer connection from cnn com wednesday esc...,comput connect from cnn com wednesday escapenu...
3,university degree obtain a prosperous future m...,university degree obtain a prosperous future m...,univers degre obtain a prosper futur money ear...
4,thanks for all your answers guys i know i shou...,thanks for all your answers guys i know i shou...,thank for all your answer guy i know i should ...

In [12]:
# Display examples

for i in range(5):

    print("ORIGINAL:")
    print(df["clean_text"].iloc[i])

    print("\nSTEMMED:")
    print(df["stemmed_text"].iloc[i])

    print("\n" + "=" * 80 + "\n")

ORIGINAL:
ounce feather bowl hummingbird opec moment alabaster valkyrie dyad bread flack desperate iambic hadron heft quell yoghurt bunkmate divert afterimage

STEMMED:
ounc feather bowl hummingbird opec moment alabast valkyri dyad bread flack desper iambic hadron heft quell yoghurt bunkmat divert afterimag

================================================================================

ORIGINAL:
wulvob get your medircations online qnb ikud viagra escapenumber escapenumber levitra escapenumber escapenumber cialis escapenumber escapenumber imitrex escapenumber escapenumber flonax escapenumber escapenumber ultram escapenumber escapenumber vioxx escapenumber escapenumber ambien escapenumber escapenumber valium escapenumber escapenumber xannax escapenumber escapenumber soma escapenumber meridia escapenumber escapenumber escapenumber escapenumber cysfrt have you ever stopped to wonder how much an average man pays for his mediecines ap painkillers drugs to improve the quality of life weight reducing tablets and many more escapenumber whats worse the same mediucine costs a lot more if it is branded rfwur are you intrested so http dmvrwm remunerativ net dfuaeirxygiq visit our website escapenumber

STEMMED:
wulvob get your medirc onlin qnb ikud viagra escapenumb escapenumb levitra escapenumb escapenumb ciali escapenumb escapenumb imitrex escapenumb escapenumb flonax escapenumb escapenumb ultram escapenumb escapenumb vioxx escapenumb escapenumb ambien escapenumb escapenumb valium escapenumb escapenumb xannax escapenumb escapenumb soma escapenumb meridia escapenumb escapenumb escapenumb escapenumb cysfrt have you ever stop to wonder how much an averag man pay for hi mediecin ap painkil drug to improv the qualiti of life weight reduc tablet and mani more escapenumb what wors the same mediucin cost a lot more if it is brand rfwur are you intrest so http dmvrwm remunerativ net dfuaeirxygiq visit our websit escapenumb

================================================================================

ORIGINAL:
computer connection from cnn com wednesday escapenumber may escapenumber escapenumber escapenumber escapenumber pm edt in this report next generation toys read brain waves google expands personalization youtube wins webby old fashioned rabbit ears laptop review next generation toys read brain waves a startup company aims to add more realistic elements to video games by using brain wave reading technology to help game developers make gaming more realistic http www cnn com escapenumber tech fun games escapenumber escapenumber mind reading toys ap index html google expands personalization google is stepping up efforts to allow its users to personalize how they search the web http www cnn com escapenumber tech internet escapenumber escapenumber google personalization reut index html youtube wins webby the co founders youtube are among the winners of the annual webby online achievement awards http www cnn com escapenumber tech internet escapenumber escapenumber webby awards ap index html old fashioned rabbit ears some consumers are spending thousands of dollars on lcd or plasma tvs and hooking them up to escapenumber antennas http www cnn com escapenumber tech ptech escapenumber escapenumber rabbit ear revival ap index html laptop review dells top shelf xps line has consistently put out distinctive laptops that feature the most advanced components on the market http www cnn com escapenumber tech ptech escapenumber escapenumber dell laptop index html cnn the most trusted name in news you have agreed to receive this email from cnn com as a result of your cnn com preference settings to manage your settings click here http audience cnn com services cnn memberservices member auth jsp url http escapenumbera escapenumberf escapelong cnn com escapelong escapenumberfcnn escapelong escapelong escapenumberfmember profile jsp escapenumberfsource escapenumberdcnn to unsubscribe from the computer connection email list click here http cgi cnn com cgi bin mail clik email ktwarwic speedy uwaterloo ca list computing read our privacy guidelines at http cnn com privacy html cable news network lp lllp one cnn center atlanta georgia escapenumber c escapenumber cable news network a time warner company all rights reserved

STEMMED:
comput connect from cnn com wednesday escapenumb may escapenumb escapenumb escapenumb escapenumb pm edt in thi report next gener toy read brain wave googl expand person youtub win webbi old fashion rabbit ear laptop review next gener toy read brain wave a startup compani aim to add more realist element to video game by use brain wave read technolog to help game develop make game more realist http www cnn com escapenumb tech fun game escapenumb escapenumb mind read toy ap index html googl expand person googl is step up effort to allow it user to person how they search the web http www cnn com escapenumb tech internet escapenumb escapenumb googl person reut index html youtub win webbi the co founder youtub are among the winner of the annual webbi onlin achiev award http www cnn com escapenumb tech internet escapenumb escapenumb webbi award ap index html old fashion rabbit ear some consum are spend thousand of dollar on lcd or plasma tv and hook them up to escapenumb antenna http www cnn com escapenumb tech ptech escapenumb escapenumb rabbit ear reviv ap index html laptop review dell top shelf xp line ha consist put out distinct laptop that featur the most advanc compon on the market http www cnn com escapenumb tech ptech escapenumb escapenumb dell laptop index html cnn the most trust name in news you have agre to receiv thi email from cnn com as a result of your cnn com prefer set to manag your set click here http audienc cnn com servic cnn memberservic member auth jsp url http escapenumbera escapenumberf escapelong cnn com escapelong escapenumberfcnn escapelong escapelong escapenumberfmemb profil jsp escapenumberfsourc escapenumberdcnn to unsubscrib from the comput connect email list click here http cgi cnn com cgi bin mail clik email ktwarwic speedi uwaterloo ca list comput read our privaci guidelin at http cnn com privaci html cabl news network lp lllp one cnn center atlanta georgia escapenumb c escapenumb cabl news network a time warner compani all right reserv

================================================================================

ORIGINAL:
university degree obtain a prosperous future money earning power and the prestige that comes with having the career position you ve always dreamed of diploma from prestigious non accredited unversities based on your present knowledge and professional experience if you qualify no required tests classes books or examinations confidentiality assured escapenumber escapenumber escapenumber escapenumber escapenumber hours a day escapenumber days a week including sundays and holidays sun escapenumber jun escapenumber escapenumber escapenumber escapenumber escapenumbershall borrowfor you have

STEMMED:
univers degre obtain a prosper futur money earn power and the prestig that come with have the career posit you ve alway dream of diploma from prestigi non accredit unvers base on your present knowledg and profession experi if you qualifi no requir test class book or examin confidenti assur escapenumb escapenumb escapenumb escapenumb escapenumb hour a day escapenumb day a week includ sunday and holiday sun escapenumb jun escapenumb escapenumb escapenumb escapenumb escapenumbershal borrowfor you have

================================================================================

ORIGINAL:
thanks for all your answers guys i know i should have checked the rsync manual but i would rather get a escapenumber sure answer from one of you this is my current script bin bash rsync avt exclude alpha exclude arm exclude hppa exclude hurd exclude iaescapenumber exclude mescapenumberk exclude mips exclude mipsel exclude multi arch exclude powerpc exclude sescapenumber exclude sh exclude sparc exclude source ftp de debian org debian cd var www mirror debian cd i know loads of excludes for now will include more distros soon from the rsync manual del an alias for delete during delete delete extraneous files from dest dirs delete before receiver deletes before transfer default delete during receiver deletes during xfer not before delete after receiver deletes after transfer not before delete excluded also delete excluded files from dest dirs which delete would you suggest i use thanks again john escapelong on escapenumber escapenumber escapenumber olleg samoylov wrote jonathan escapelong wrote sorry for the banal question my favourite keys for escapenumber stage rsync rsync verbose recursive links hard links times filter r tmp delete after delay updates source url destination log file olleg samoylov www escapelong org mirror escapelong org rcrack escapelong org ninux org wireless community rome

STEMMED:
thank for all your answer guy i know i should have check the rsync manual but i would rather get a escapenumb sure answer from one of you thi is my current script bin bash rsync avt exclud alpha exclud arm exclud hppa exclud hurd exclud iaescapenumb exclud mescapenumberk exclud mip exclud mipsel exclud multi arch exclud powerpc exclud sescapenumb exclud sh exclud sparc exclud sourc ftp de debian org debian cd var www mirror debian cd i know load of exclud for now will includ more distro soon from the rsync manual del an alia for delet dure delet delet extran file from dest dir delet befor receiv delet befor transfer default delet dure receiv delet dure xfer not befor delet after receiv delet after transfer not befor delet exclud also delet exclud file from dest dir which delet would you suggest i use thank again john escapelong on escapenumb escapenumb escapenumb olleg samoylov wrote jonathan escapelong wrote sorri for the banal question my favourit key for escapenumb stage rsync rsync verbos recurs link hard link time filter r tmp delet after delay updat sourc url destin log file olleg samoylov www escapelong org mirror escapelong org rcrack escapelong org ninux org wireless commun rome

================================================================================

In [13]:
# Compare vocabulary size

original_vocab = set(
    " ".join(df["clean_text"]).split()
)

stemmed_vocab = set(
    " ".join(df["stemmed_text"]).split()
)

print("Original Vocabulary Size:", len(original_vocab))
print("Stemmed Vocabulary Size:", len(stemmed_vocab))

Original Vocabulary Size: 292833
Stemmed Vocabulary Size: 245602

####  Limitations of Stemming

Stemming is simple and fast, but it has several limitations.

##### Invalid Words

A stem may not be a real English word.

```text
studies → studi