### Sentence Tokenization in NLP

Sentence Tokenization is the process of splitting a paragraph or document into individual sentences.

#### Why Do We Need Sentence Tokenization?

A document or email can contain multiple sentences.

Instead of processing the entire document as one large piece of text, we can split it into individual sentences.

#### Download NLTK Sentence Tokenization Resource

NLTK provides a pre-trained sentence tokenizer that can identify sentence boundaries.

We will use the `punkt` tokenizer.

In [6]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to C:\Users\Pickus
[nltk_data]     Games\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Pickus
[nltk_data]     Games\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

#### Basic Sentence Tokenization

We can use NLTK's `sent_tokenize()` function to split text into individual sentences.

In [7]:
from nltk.tokenize import word_tokenize

text = "Hello brother. I am learning NLP."

tokens = word_tokenize(text)

print(tokens)

['Hello', 'brother', '.', 'I', 'am', 'learning', 'NLP', '.']

In [9]:
from nltk.tokenize import sent_tokenize

text = "I love Python. I am learning NLP. NLP is interesting!"

sentences = sent_tokenize(text)

for i, sentence in enumerate(sentences, start=1):
    print(f"Sentence {i}: {sentence}")

Sentence 1: I love Python.
Sentence 2: I am learning NLP.
Sentence 3: NLP is interesting!

#### Count the Number of Sentences

After tokenization, we can easily calculate how many sentences are present in a piece of text.

In [10]:
print("Number of sentences:", len(sentences))

Number of sentences: 3

#### Load the data

In [11]:
import pandas as pd
# Load dataset
df = pd.read_csv(r"F:\Anas\DATA_SCIENCE_PROJECTS\DATASETS\combined_data.csv")
df.head()

   label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

In [12]:
# Display the column names

print(df.columns)

Index(['label', 'text'], dtype='str')

#### Create a Sentence Tokenization Function

We can create a reusable function that takes an email and returns a list of sentences.

This allows us to apply the same process to every email in the dataset.

In [13]:
def sentence_tokenize(text):
    return sent_tokenize(str(text))

In [14]:
df["sentences"] = df["text"].apply(sentence_tokenize)

df[["text", "sentences"]].head()

,text,sentences
0,ounce feather bowl hummingbird opec moment ala...,[ounce feather bowl hummingbird opec moment al...
1,wulvob get your medircations online qnb ikud v...,[wulvob get your medircations online qnb ikud ...
2,computer connection from cnn com wednesday es...,[ computer connection from cnn com wednesday e...
3,university degree obtain a prosperous future m...,[university degree obtain a prosperous future ...
4,thanks for all your answers guys i know i shou...,[thanks for all your answers guys i know i sho...

#### Inspect Individual Sentences

Let's inspect one email and display each sentence separately.

In [15]:
email = df["text"].iloc[0]

sentences = sent_tokenize(str(email))

print("Original Email:")
print(email)

print("\n" + "=" * 60)

print("Individual Sentences:")

for i, sentence in enumerate(sentences, start=1):
    print(f"{i}. {sentence}")

Original Email:
ounce feather bowl hummingbird opec moment alabaster valkyrie dyad bread flack desperate iambic hadron heft quell yoghurt bunkmate divert afterimage

============================================================
Individual Sentences:
1. ounce feather bowl hummingbird opec moment alabaster valkyrie dyad bread flack desperate iambic hadron heft quell yoghurt bunkmate divert afterimage